version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - minha-rede

  go-app:
    image: juanarsam/hackgolang:latest
    container_name: go-app
    ports:
      - "9080:9080"
    networks:
      - minha-rede
    depends_on:
      - mongodb

networks:
  minha-rede:
    driver: bridge

volumes:
  mongo_data: